services:
  db:
    image: postgres:16
    container_name: segapp_db
    environment:
      POSTGRES_USER: segapp
      POSTGRES_PASSWORD: segapp
      POSTGRES_DB: segapp
    volumes:
      - segapp_pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  segapp_pg:
